import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion'

import { Container } from '@/components/layout/Container'
import { Section } from '@/components/layout/Section'

const faqs = [
  {
    question: 'Is QRHub completely free?',
    answer: 'Yes. You can generate and download QR codes for free without creating an account.',
  },
  {
    question: 'Do I need to sign up?',
    answer: 'No. QRHub is designed for instant use with no registration required.',
  },
  {
    question: 'Can I download PNG and SVG?',
    answer: 'Yes. High-quality PNG and SVG downloads are supported.',
  },
  {
    question: 'Will my QR codes expire?',
    answer: 'No. Static QR codes generated by QRHub never expire.',
  },
  {
    question: 'Can I customize colors and logos?',
    answer: 'Yes. Advanced customization options are available in the QR generator.',
  },
]

export function FAQ() {
  return (
    <Section id="faq">
      <Container>
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="text-4xl font-bold tracking-tight">Frequently Asked Questions</h2>

          <p className="mt-4 text-lg text-muted-foreground">
            Everything you need to know about QRHub.
          </p>
        </div>

        <div className="mx-auto mt-16 max-w-3xl">
          <Accordion type="single" collapsible>
            {faqs.map((faq) => (
              <AccordionItem key={faq.question} value={faq.question}>
                <AccordionTrigger>{faq.question}</AccordionTrigger>

                <AccordionContent>{faq.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </Container>
    </Section>
  )
}
